server:
  port: 8765
  
spring:
  application:
    name: hr-gateway
  cloud:
    gateway:
      routes:
        - id: hr-worker
          uri: lb://hr-worker
          predicates:
            - Path=/hr-worker/**
        - id: hr-payroll
          uri: lb://hr-payroll
          predicates:
            - Path=/hr-payroll/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      httpclient:
        connect-timeout: 5000
        response-timeout: 5s
      default-filters:
        - RemoveRequestHeader=Cookie
        - RemoveRequestHeader=Set-Cookie
        - RemoveRequestHeader=Authorization

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
    hostname: localhost    
