server:
  port: ${PORT:0}

spring:
  application:
    name: hr-worker

  cloud:
    config:
      uri: http://${CONFIG_SERVER_HOST:localhost}:${CONFIG_SERVER_PORT:8888}/hr-oauth

  config:
    import: configserver:http://${CONFIG_SERVER_HOST:localhost}:${CONFIG_SERVER_PORT:8888}/
    import-check:
      enabled: false

  profiles:
    active: dev

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOST:localhost}:${EUREKA_SERVER_PORT:8761}/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    preferIpAddress: true
    hostname: ${HOST_NAME:localhost}

management:
  endpoints:
    web:
      exposure:
        include: "*"
