server:
  port: ${PORT:0}

spring:
  application:
    name: hr-oauth
    
  cloud:
    config:
      uri: ${CONFIG_SERVER_URL:http://localhost:8888/}${spring.application.name}
      
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
    import-check:
      enabled: false
  
  profiles:
    active: dev

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*"